services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=dustydocs'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '2345:2345'

  ollama:
    hostname: ollama
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
