spring:
  application:
    name: dusty

  datasource:
    url: jdbc:postgresql://localhost:2345/dustydocs
    username: admin
    password: secret

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: tinyllama

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: cosine_distance
        dimensions: 1536

